version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      -  ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}

  web:
    build: .
    depends_on:
      - db 
    ports:
      - "8080:8080"

